name: Flutter Action
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: "16.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.8


      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk
      - uses: actions/upload-artifact@v4
        with:
          name: app
          files: build/app/outputs/apk/flutter-apk/app-release.apk
#          files: build/app/outputs/flutter-apk/app-release.apk

